enableTransparentWorkspaces: false

nmHoistingLimits: workspaces

nodeLinker: node-modules
checksumBehavior: update

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs