// import { selectLibraryWithRelations } from '@/db/media/actions/libraries';

// import { mediaDb } from '@/db/media';
// import { tracks } from '@/db/media/schema/tracks';
// import { eq, like } from 'drizzle-orm';
// import { rmSync } from 'fs';


// import { mkdirSync, readdirSync, renameSync } from 'fs';
// import { parseYear } from '../dateTime';

// import { mediaDb } from '@/db/media';
// import { insertLibraryMovie } from '@/db/media/actions/library_movie';


export default () => {

	// const Tracks = mediaDb.query.tracks.findMany({
	// 	where: like(tracks.filename, '% (2).%'),
	// });

	// for (const track of Tracks) {
	// 	rmSync(track.path);
	// 	mediaDb.delete(tracks)
	// 		.where(eq(tracks.id, track.id))
	// 		.run();
	// }

	// const folder = 'M:\\TV.Shows\\TV.Shows\\Tom.and.Jerry.(1940)';
	// readdirSync(folder).forEach((f) => {
	// 	const name = `${folder}\\${f}`;
	// 	const item = tjJson.find(t => name.includes(t.Name));
	// 	const year = parseYear(item?.Airdate);
	// 	mkdirSync('M:\\Films\\Download\\Tom.and.Jerry', { recursive: true });

	// 	console.log({
	// 		// item: item,
	// 		path: name,
	// 		newFile: `M:\\Films\\Download\\Tom.and.Jerry\\${item?.Name} (${year}).mkv`,
	// 	});

	// 	renameSync(name, `M:\\Films\\Download\\Tom.and.Jerry\\${item?.Name} (${year}).mkv`);
	// });

	// console.log(selectLibraryWithRelations());

	// try {

	// 	const data = mediaDb.query.movies.findMany({
	// 		// where: eq(libraries.id, req.params.id),
	// 		// with: {
	// 		// 	folder_library: true,
	// 		// },
	// 	});

	// 	for (const movie of data) {
	// 		insertLibraryMovie({
	// 			library_id: movie.library_id,
	// 			movie_id: movie.id,
	// 		});
	// 	}
	// } catch (error) {
	// 	console.log(error);
	// }

	// const ModelName = [
	// 	'configuration',
	// 	'libraries',
	// 	'encoderProfiles',
	// 	'subtitleLanguages',
	// 	'languages',
	// 	'metadata',
	// 	'libraryFolders',
	// 	'folders',
	// 	'providers',
	// 	'countries',
	// 	'activityLogs',
	// 	'devices',
	// 	'runningTasks',
	// 	'users',
	// 	'files',
	// 	'mediaAttachments',
	// 	'mediastreams',
	// 	'userData',
	// 	'alternativeTitles',
	// 	'casts',
	// 	'roles',
	// 	'certifications',
	// 	'creators',
	// 	'crews',
	// 	'jobs',
	// 	'episodes',
	// 	'guestStars',
	// 	'keywords',
	// 	'messages',
	// 	'movies',
	// 	'collections',
	// 	'genres',
	// 	'people',
	// 	'recommendations',
	// 	'seasons',
	// 	'similars',
	// 	'specials',
	// 	'specialItems',
	// 	'translations',
	// 	'tvs',
	// 	'videoFiles',
	// 	'images',
	// 	'medias',
	// 	'artists',
	// 	'albums',
	// 	'musicGenres',
	// 	'tracks',
	// 	'playlists',
	// ];

	// for (const db of ModelName) {
	// 	const file = resolve('src', 'db', 'schema', 'media', `${db}.ts`);
	// 	if (!existsSync(file)) {
	// 		writeFileSync(file, `
	// 		import { boolean, datetime } from '../../helpers';
	// 		import { sql } from 'drizzle-orm';
	// 		import { text, sqliteTable } from 'drizzle-orm/sqlite-core';

	// 		export const ${db} = sqliteTable('${db}', {
	// 			id: text('id'),
	// 		});
	// 		`);
	// 	};
	// };


	// const posters: {title: string; src: string}[] = [];
	// const backdrops: {title: string; src: string}[] = [];
	// const profiles: {title: string; src: string}[] = [];

	// await confDb.media.findMany({
	// 	where: {
	// 		type: 'poster',
	// 		tvId: {
	// 			not: null,
	// 		},
	// 	},
	// 	take: 250,
	// 	include: {
	// 		Tv: true,
	// 	},
	// 	orderBy: {
	// 		voteAverage: 'desc',
	// 	},
	// }).then((data) => {
	// 	unique(data, 'tvId').forEach((d) => {
	// 		if (d.src) {
	// 			posters.push({
	// 				title: d.Tv!.title,
	// 				src: d.src,
	// 			});
	// 		}
	// 	});
	// });
	// await confDb.media.findMany({
	// 	where: {
	// 		type: 'poster',
	// 		movieId: {
	// 			not: null,
	// 		},
	// 	},
	// 	take: 250,
	// 	include: {
	// 		Movie: true,
	// 	},
	// 	orderBy: {
	// 		voteAverage: 'desc',
	// 	},
	// }).then((data) => {
	// 	unique(data, 'movieId').forEach((d) => {
	// 		if (d.src) {
	// 			posters.push({
	// 				title: d.Movie!.title,
	// 				src: d.src,
	// 			});
	// 		}
	// 	});
	// });
	// await confDb.media.findMany({
	// 	where: {
	// 		type: 'backdrop',
	// 		tvId: {
	// 			not: null,
	// 		},
	// 	},
	// 	take: 250,
	// 	include: {
	// 		Tv: true,
	// 	},
	// 	orderBy: {
	// 		voteAverage: 'desc',
	// 	},
	// }).then((data) => {
	// 	unique(data, 'tvId').forEach((d) => {
	// 		if (d.src) {
	// 			backdrops.push({
	// 				title: d.Tv!.title,
	// 				src: d.src,
	// 			});
	// 		}
	// 	});
	// });
	// await confDb.media.findMany({
	// 	where: {
	// 		type: 'backdrop',
	// 		movieId: {
	// 			not: null,
	// 		},
	// 	},
	// 	take: 250,
	// 	include: {
	// 		Movie: true,
	// 	},
	// 	orderBy: {
	// 		voteAverage: 'desc',
	// 	},
	// }).then((data) => {
	// 	unique(data, 'movieId').forEach((d) => {
	// 		if (d.src) {
	// 			backdrops.push({
	// 				title: d.Movie!.title,
	// 				src: d.src,
	// 			});
	// 		}
	// 	});
	// });
	// await confDb.media.findMany({
	// 	where: {
	// 		type: 'profile',
	// 		personId: {
	// 			not: null,
	// 		},
	// 	},
	// 	include: {
	// 		Person: true,
	// 	},
	// 	take: 500,
	// 	orderBy: {
	// 		voteAverage: 'desc',
	// 	},
	// }).then((data) => {
	// 	unique(data, 'personId').forEach((d) => {
	// 		if (d.src) {
	// 			profiles.push({
	// 				title: d.Person!.name!,
	// 				src: d.src,
	// 			});
	// 		}
	// 	});
	// });

	// writeFileSync('figmaData.json', JSON.stringify({ posters, backdrops, profiles }));


	// const folder = 'D:/TV.Shows/Download/NCIS.(2003)';
	// const libraryId = 'cl7i4km1o0008qwef7qwdapxe';

	// const library = await confDb.library.findFirst({
	// 	where: {
	// 		id: libraryId,
	// 	},
	// 	include: {
	// 		EncoderProfiles: {
	// 			include: {
	// 				EncoderProfile: true,
	// 			},
	// 		},
	// 		Folders: {
	// 			include: {
	// 				folder: true,
	// 			},
	// 		},
	// 	},
	// });

	// const episodes = readdirSync(folder)
	// 	.map((f) => {
	// 		return {
	// 			path: `${folder}/${f}`,
	// 		};
	// 	})
	// 	.filter(f => f.path.endsWith('.mkv'));

	// for (const episode of episodes) {
	// 	try {
	// 		const onDemand = new FFMpegArchive();

	// 		onDemand.setLibrary(library!);
	// 		await onDemand.fromFile(episode.path);

	// 		onDemand
	// 			.verify()
	// 			.makeStack()
	// 			// .check();

	// 		if (onDemand.commands.length == 0) {
	// 			console.error('No commands to execute');
	// 		} else {
	// 			await onDemand.start(() => onDemand.buildSprite());
	// 		}
	// 	} catch (e) {
	// 		console.error(e);
	// 	}
	// };


	// const folder = 'D:/TV.Shows/Download/NCIS.(2003)';
	// const episodes = readdirSync(folder).map((f) => {
	// 	return {
	// 		path: `${folder}/${f}`,
	// 	};
	// });
	// await Promise.all([
	// await encodeFolder({ folder: 'M:/Films/Films/Cosmos.Laundromat.(2015)/original', libraryId: 'cl7i4km1o0006qwefdx5neusi' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/NCIS.(2003)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/Family.Guy.(1999)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/Love.Death.and.Robots.(2019)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/American.Dad.(2005)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/Rick.and.Morty.(2013)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/South.Park.(1997)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/The.Blacklist.(2013)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/The.Sandman.(2022)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/The.Cleveland.Show.(2009)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/Scooby-Doo.and.Scrappy-Doo.(1979)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/Popeye.the.Sailor.(1960)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/Dexter\'s.Laboratory.(1996)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// await encodeFolder({ folder: 'D:/TV.Shows/Download/NCIS.New.Orleans.(2014)', libraryId: 'cl7i4km1o0008qwef7qwdapxe' });
	// ]);

	// const fp = new FFmpegWrapper();

	// for (const episode of episodes.slice(0, 1)) {
	// 	await fp.open(episode);
	// 	await fp.detectSilence();
	// 	// const args = fp.silenceRanges.filter(s => s.duration > 1).map(s => ({ start: s.start, end: s.end }))[0];
	// 	writeFileSync('detect.json', JSON.stringify(fp, null, 2));
	// 	console.log(fp);
	// }

	// ripper();

	// const library = await confDb.library.findFirst({
	// 	where: {
	// 		id: 'cl7i4km1o0008qwef7qwdapxe',
	// 	},
	// 	include: {
	// 		EncoderProfiles: {
	// 			include: {
	// 				EncoderProfile: true,
	// 			},
	// 		},
	// 		Folders: {
	// 			include: {
	// 				folder: true,
	// 			},
	// 		},
	// 	},
	// });

	// confDb.similar.findMany({
	// 	where: {
	// 		OR: [
	// 			{
	// 				blurHash: null,
	// 			},
	// 			{
	// 				colorPalette: null,
	// 			},
	// 		],
	// 	},
	// })
	// 	.then(async (shows) => {

	// 		console.log(`Found ${shows.length} images to make blurHashes for`);

	// 		for (const tv of shows) {
	// 			console.log(`Making blurHash: ${tv.poster}`);

	// 			const palette: any = {
	// 				poster: undefined,
	// 				backdrop: undefined,
	// 			};

	// 			const blurHash: any = {
	// 				poster: undefined,
	// 				backdrop: undefined,
	// 			};

	// 			await Promise.all([
	// 				tv.poster && createBlurHash(`https://image.tmdb.org/t/p/w185${tv.poster}`).then((hash) => {
	// 					blurHash.poster = hash;
	// 				}),
	// 				tv.backdrop && createBlurHash(`https://image.tmdb.org/t/p/w185${tv.backdrop}`).then((hash) => {
	// 					blurHash.backdrop = hash;
	// 				}),
	// 				tv.poster && colorPalette(`https://image.tmdb.org/t/p/w185${tv.poster}`).then((hash) => {
	// 					palette.poster = hash;
	// 				}),
	// 				tv.backdrop && colorPalette(`https://image.tmdb.org/t/p/w185${tv.backdrop}`).then((hash) => {
	// 					palette.backdrop = hash;
	// 				}),
	// 			]);

	// 			await confDb.similar.update({
	// 				where: {
	// 					id: tv.id,
	// 				},
	// 				data: {
	// 					colorPalette: JSON.stringify(palette),
	// 					blurHash: JSON.stringify(blurHash),
	// 				},
	// 			});
	// 		};
	// 	})
	// 	.finally(() => {
	// 		console.log('Done making all blurHashes');
	// 	});

	// confDb.movie.findMany()
	// 	.then(async (movies) => {
	// 		for (const movie of movies) {
	// 			console.log(`Deleting Movie: ${movie.title} (${movie.id})`);
	// 			await confDb.movie.delete({
	// 				where: {
	// 					id: movie.id,
	// 				},
	// 			});
	// 		}
	// 	})
	// 	.finally(() => {
	// 		console.log('Done deleting all movies');
	// 	});

	// confDb.person.findMany()
	// 	.then(async (persons) => {
	// 		for (const person of persons) {
	// 			console.log(`Deleting person: ${person.name} (${person.id})`);
	// 			await confDb.person.delete({
	// 				where: {
	// 					id: person.id,
	// 				},
	// 			});
	// 		}
	// 	})
	// 	.finally(() => {
	// 		console.log('Done deleting all people');
	// 	});
	// confDb.image.findMany()
	// 	.then(async (images) => {
	// 		for (const image of images) {
	// 			console.log(`Deleting image: ${image.name} (${image.id})`);
	// 			await confDb.image.delete({
	// 				where: {
	// 					id: image.id,
	// 				},
	// 			});
	// 		}
	// 	})
	// 	.finally(() => {
	// 		console.log('Done deleting all images');
	// 	});
	// confDb.translation.findMany()
	// 	.then(async (translations) => {
	// 		for (const translation of translations) {
	// 			console.log(`Deleting translation: ${translation.title} (${translation.id})`);
	// 			await confDb.translation.delete({
	// 				where: {
	// 					id: translation.id,
	// 				},
	// 			});
	// 		}
	// 	})
	// 	.finally(() => {
	// 		console.log('Done deleting all translations');
	// 	});

	// const transaction: any[] = [];

	// const movies = await confDb.movie.findMany({
	// 	select: {
	// 		id: true,
	// 	},
	// }).then(movie => movie.map(m => m.id));

	// const tvs = await confDb.tv.findMany({
	// 	select: {
	// 		id: true,
	// 	},
	// }).then(tv => tv.map(m => m.id));

	// const similars = await confDb.similar.findMany();
	// for (const similar of similars ?? []) {
	// 	if (similar.mediaType == 'movie') {
	// 		transaction.push(confDb.similar.update({
	// 			where: {
	// 				id: similar.id,
	// 			},
	// 			data: {
	// 				MovieFrom: {
	// 					connect: {
	// 						id: similar.similarableId,
	// 					},
	// 				},
	// 			},
	// 		}));
	// 		if (movies.includes(similar.mediaId)) {
	// 			transaction.push(confDb.similar.update({
	// 				where: {
	// 					id: similar.id,
	// 				},
	// 				data: {
	// 					MovieTo: {
	// 						connect: {
	// 							id: similar.mediaId,
	// 						},
	// 					},
	// 				},
	// 			}));
	// 		}
	// 	} else {
	// 		transaction.push(confDb.similar.update({
	// 			where: {
	// 				id: similar.id,
	// 			},
	// 			data: {
	// 				TvFrom: {
	// 					connect: {
	// 						id: similar.similarableId,
	// 					},
	// 				},
	// 			},
	// 		}));

	// 		if (tvs.includes(similar.mediaId)) {
	// 			transaction.push(confDb.similar.update({
	// 				where: {
	// 					id: similar.id,
	// 				},
	// 				data: {
	// 					TvTo: {
	// 						connect: {
	// 							id: similar.mediaId,
	// 						},
	// 					},
	// 				},
	// 			}));
	// 		}
	// 	}
	// }

	// const recommendations = await confDb.recommendation.findMany();
	// for (const recommendation of recommendations ?? []) {
	// 	if (recommendation.mediaType == 'movie') {
	// 		transaction.push(confDb.recommendation.update({
	// 			where: {
	// 				id: recommendation.id,
	// 			},
	// 			data: {
	// 				MovieFrom: {
	// 					connect: {
	// 						id: recommendation.recommendationableId,
	// 					},
	// 				},
	// 			},
	// 		}));

	// 		if (movies.includes(recommendation.mediaId)) {
	// 			transaction.push(confDb.recommendation.update({
	// 				where: {
	// 					id: recommendation.id,
	// 				},
	// 				data: {
	// 					MovieTo: {
	// 						connect: {
	// 							id: recommendation.mediaId,
	// 						},
	// 					},
	// 				},
	// 			}));
	// 		}
	// 	} else {
	// 		transaction.push(confDb.recommendation.update({
	// 			where: {
	// 				id: recommendation.id,
	// 			},
	// 			data: {
	// 				TvFrom: {
	// 					connect: {
	// 						id: recommendation.recommendationableId,
	// 					},
	// 				},
	// 			},
	// 		}));

	// 		if (tvs.includes(recommendation.mediaId)) {
	// 			transaction.push(confDb.recommendation.update({
	// 				where: {
	// 					id: recommendation.id,
	// 				},
	// 				data: {
	// 					TvTo: {
	// 						connect: {
	// 							id: recommendation.mediaId,
	// 						},
	// 					},
	// 				},
	// 			}));
	// 		}
	// 	}
	// }

	// await confDb.$transaction(transaction);

};

export const tjJson = [
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '47',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Purr-Chance to Dream',
	  'Size': '0.00 B',
	  'Airdate': '09/07/1967, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '46',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Advance and Be Mechanized',
	  'Size': '0.00 B',
	  'Airdate': '08/29/1967, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '45',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Shutter-Bugged Cat',
	  'Size': '0.00 B',
	  'Airdate': '06/18/1967, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '44',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Surf-Bored Cat',
	  'Size': '0.00 B',
	  'Airdate': '06/04/1967, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '43',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Mouse from H.U.N.G.E.R.',
	  'Size': '0.00 B',
	  'Airdate': '05/07/1967, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '42',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Cannery Rodent',
	  'Size': '0.00 B',
	  'Airdate': '04/16/1967, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '41',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Rock \'N\' Rodent',
	  'Size': '0.00 B',
	  'Airdate': '03/22/1967, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '40',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Guided Mouse-ille',
	  'Size': '0.00 B',
	  'Airdate': '02/03/1967, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '39',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'O-Solar-Meow',
	  'Size': '0.00 B',
	  'Airdate': '01/29/1967, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '38',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Cat and Dupli-Cat',
	  'Size': '0.00 B',
	  'Airdate': '01/16/1967, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '37',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Catty-Cornered',
	  'Size': '0.00 B',
	  'Airdate': '09/10/1966, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '36',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The A-TOM-iNABLE Snowman',
	  'Size': '0.00 B',
	  'Airdate': '06/20/1966, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '35',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Matinee Mouse',
	  'Size': '0.00 B',
	  'Airdate': '05/09/1966, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '34',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Filet Meow',
	  'Size': '0.00 B',
	  'Airdate': '04/18/1966, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '33',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Puss \'N\' Boats',
	  'Size': '0.00 B',
	  'Airdate': '03/21/1966, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '32',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Love Me, Love My Mouse',
	  'Size': '0.00 B',
	  'Airdate': '02/14/1966, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '31',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Jerry-Go-Round',
	  'Size': '0.00 B',
	  'Airdate': '01/20/1966, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '30',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Jerry, Jerry, Quite Contrary',
	  'Size': '0.00 B',
	  'Airdate': '01/14/1966, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '29',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Duel Personality',
	  'Size': '0.00 B',
	  'Airdate': '01/08/1966, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '28',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Cat\'s Me-Ouch',
	  'Size': '0.00 B',
	  'Airdate': '12/22/1965, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '27',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Year of the Mouse',
	  'Size': '0.00 B',
	  'Airdate': '05/17/1965, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '26',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Of Feline Bondage',
	  'Size': '0.00 B',
	  'Airdate': '04/26/1965, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '25',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'I\'m Just Wild About Jerry',
	  'Size': '0.00 B',
	  'Airdate': '04/05/1965, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '24',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Haunted Mouse',
	  'Size': '0.00 B',
	  'Airdate': '03/29/1965, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '23',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Brothers Carry-Mouse-Off',
	  'Size': '0.00 B',
	  'Airdate': '02/22/1965, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '22',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Bad Day at Cat Rock',
	  'Size': '0.00 B',
	  'Airdate': '01/24/1965, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '21',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom-ic Energy',
	  'Size': '0.00 B',
	  'Airdate': '01/11/1965, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '20',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Ah, Sweet Mouse-Story of Life',
	  'Size': '0.00 B',
	  'Airdate': '01/03/1965, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '19',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Unshrinkable Jerry Mouse',
	  'Size': '0.00 B',
	  'Airdate': '09/02/1964, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '18',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Snowbody Loves Me',
	  'Size': '0.00 B',
	  'Airdate': '02/11/1964, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '17',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Much Ado About Mousing',
	  'Size': '0.00 B',
	  'Airdate': '01/29/1964, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '16',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Is There a Doctor in the Mouse?',
	  'Size': '0.00 B',
	  'Airdate': '01/22/1964, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '15',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Cat Above and the Mouse Below',
	  'Size': '0.00 B',
	  'Airdate': '01/01/1964, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '14',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Pent-House Mouse',
	  'Size': '0.00 B',
	  'Airdate': '07/27/1963, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '13',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Carmen Get It!',
	  'Size': '0.00 B',
	  'Airdate': '12/01/1962, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '12',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Buddies Thicker Than Water',
	  'Size': '0.00 B',
	  'Airdate': '11/01/1962, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '11',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Sorry Safari',
	  'Size': '0.00 B',
	  'Airdate': '10/01/1962, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '10',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tall in the Trap',
	  'Size': '0.00 B',
	  'Airdate': '09/01/1962, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '9',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Tom and Jerry Cartoon Kit',
	  'Size': '0.00 B',
	  'Airdate': '08/01/1962, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '8',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Dicky Moe',
	  'Size': '0.00 B',
	  'Airdate': '07/01/1962, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '7',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Calypso Cat',
	  'Size': '0.00 B',
	  'Airdate': '06/01/1962, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '6',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Landing Stripling',
	  'Size': '0.00 B',
	  'Airdate': '04/01/1962, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '5',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Mouse into Space',
	  'Size': '0.00 B',
	  'Airdate': '02/01/1962, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '4',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'High Steaks',
	  'Size': '0.00 B',
	  'Airdate': '01/01/1962, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '3',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'It\'s Greek to Me-Ow!',
	  'Size': '0.00 B',
	  'Airdate': '12/07/1961, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '2',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Down and Outing',
	  'Size': '0.00 B',
	  'Airdate': '10/26/1961, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '1',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Switchin\' Kitten',
	  'Size': '0.00 B',
	  'Airdate': '09/07/1961, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': 'NFO',
	  'TBN': 'TBN',
	  'Episode': 'Episode',
	  'Absolute': 'Absolute',
	  'Scene Season/Episode': 'Scene Season/Episode',
	  'Scene Absolute': 'Scene Absolute',
	  'Name': 'Name',
	  'Size': 'Size',
	  'Airdate': 'Airdate',
	  'Download': 'Download',
	  'Subtitles': 'Subtitles',
	  'Status': 'Status',
	  'Search': 'Search',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '68',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tot Watchers',
	  'Size': '0.00 B',
	  'Airdate': '08/01/1958, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '67',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Robin Hoodwinked',
	  'Size': '0.00 B',
	  'Airdate': '06/06/1958, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '66',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Vanishing Duck',
	  'Size': '0.00 B',
	  'Airdate': '05/02/1958, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '65',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Royal Cat Nap',
	  'Size': '0.00 B',
	  'Airdate': '03/07/1958, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '64',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Happy Go Ducky',
	  'Size': '0.00 B',
	  'Airdate': '01/03/1958, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '63',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom\'s Photo Finish',
	  'Size': '0.00 B',
	  'Airdate': '11/01/1957, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '62',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Mucho Mouse',
	  'Size': '0.00 B',
	  'Airdate': '09/06/1957, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '61',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Feedin\' The Kiddie',
	  'Size': '0.00 B',
	  'Airdate': '06/07/1957, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '60',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Timid Tabby',
	  'Size': '0.00 B',
	  'Airdate': '04/19/1957, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '59',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tops With Pops',
	  'Size': '0.00 B',
	  'Airdate': '02/22/1957, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '58',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Barbecue Brawl',
	  'Size': '0.00 B',
	  'Airdate': '12/14/1956, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '57',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Blue Cat Blues',
	  'Size': '0.00 B',
	  'Airdate': '11/06/1956, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '56',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Down Beat Bear',
	  'Size': '0.00 B',
	  'Airdate': '10/21/1956, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '55',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Muscle Beach Tom',
	  'Size': '0.00 B',
	  'Airdate': '09/07/1956, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '54',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Busy Buddies',
	  'Size': '0.00 B',
	  'Airdate': '05/04/1956, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '53',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Egg And Jerry',
	  'Size': '0.00 B',
	  'Airdate': '03/23/1956, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '52',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Flying Sorceress',
	  'Size': '0.00 B',
	  'Airdate': '01/27/1956, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '51',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'That\'s My Mommy',
	  'Size': '0.00 B',
	  'Airdate': '11/19/1955, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '50',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Pecos Pest',
	  'Size': '0.00 B',
	  'Airdate': '11/11/1955, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '49',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Smarty Cat',
	  'Size': '0.00 B',
	  'Airdate': '10/14/1955, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '48',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom And Chérie',
	  'Size': '0.00 B',
	  'Airdate': '09/09/1955, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '47',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Designs On Jerry',
	  'Size': '0.00 B',
	  'Airdate': '09/02/1955, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '46',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Mouse For Sale',
	  'Size': '0.00 B',
	  'Airdate': '05/21/1955, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '45',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Pup On A Picnic',
	  'Size': '0.00 B',
	  'Airdate': '04/30/1955, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '44',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Southbound Duckling',
	  'Size': '0.00 B',
	  'Airdate': '03/12/1955, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '43',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Touché, Pussy Cat!',
	  'Size': '0.00 B',
	  'Airdate': '12/18/1954, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '42',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Pet Peeve',
	  'Size': '0.00 B',
	  'Airdate': '11/20/1954, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '41',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Downhearted Duckling',
	  'Size': '0.00 B',
	  'Airdate': '11/13/1954, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '40',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Neapolitan Mouse',
	  'Size': '0.00 B',
	  'Airdate': '10/02/1954, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '39',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Mice Follies',
	  'Size': '0.00 B',
	  'Airdate': '09/04/1954, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '38',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Baby Butch',
	  'Size': '0.00 B',
	  'Airdate': '03/14/1954, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '37',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Little School Mouse',
	  'Size': '0.00 B',
	  'Airdate': '05/29/1954, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '36',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Hic-cup Pup',
	  'Size': '0.00 B',
	  'Airdate': '04/17/1954, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '35',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Posse Cat',
	  'Size': '0.00 B',
	  'Airdate': '01/30/1954, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '34',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Puppy Tale',
	  'Size': '0.00 B',
	  'Airdate': '01/23/1954, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '33',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Life With Tom',
	  'Size': '0.00 B',
	  'Airdate': '11/21/1953, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '32',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Two Little Indians',
	  'Size': '0.00 B',
	  'Airdate': '10/17/1953, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '31',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Just Ducky',
	  'Size': '0.00 B',
	  'Airdate': '09/05/1953, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '30',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'That\'s My Pup!',
	  'Size': '0.00 B',
	  'Airdate': '04/25/1953, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '29',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Johann Mouse',
	  'Size': '0.00 B',
	  'Airdate': '03/21/1953, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '28',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Jerry And Jumbo',
	  'Size': '0.00 B',
	  'Airdate': '02/21/1953, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '27',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Missing Mouse',
	  'Size': '0.00 B',
	  'Airdate': '01/10/1953, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '26',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Dog House',
	  'Size': '0.00 B',
	  'Airdate': '11/29/1952, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '25',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Cruise Cat',
	  'Size': '0.00 B',
	  'Airdate': '10/18/1952, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '24',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Push-Button Kitty',
	  'Size': '0.00 B',
	  'Airdate': '09/06/1952, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '23',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Fit To Be Tied',
	  'Size': '0.00 B',
	  'Airdate': '07/26/1952, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '22',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Little Runaway',
	  'Size': '0.00 B',
	  'Airdate': '06/14/1952, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '21',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Triplet Trouble',
	  'Size': '0.00 B',
	  'Airdate': '04/19/1952, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '20',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Smitten Kitten',
	  'Size': '0.00 B',
	  'Airdate': '04/12/1952, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '19',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Two Mouseketeers',
	  'Size': '0.00 B',
	  'Airdate': '03/15/1952, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '18',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Duck Doctor',
	  'Size': '0.00 B',
	  'Airdate': '02/16/1952, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '17',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Flying Cat',
	  'Size': '0.00 B',
	  'Airdate': '01/12/1952, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '16',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Cat Napping',
	  'Size': '0.00 B',
	  'Airdate': '12/08/1951, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '15',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Nit-Witty Kitty',
	  'Size': '0.00 B',
	  'Airdate': '10/06/1951, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '14',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Slicked-Up Pup',
	  'Size': '0.00 B',
	  'Airdate': '09/08/1951, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '13',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'His Mouse Friday',
	  'Size': '0.00 B',
	  'Airdate': '07/07/1951, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '12',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Sleepy-Time Tom',
	  'Size': '0.00 B',
	  'Airdate': '05/26/1951, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '11',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Jerry\'s Cousin',
	  'Size': '0.00 B',
	  'Airdate': '04/07/1951, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '10',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Jerry And The Goldfish',
	  'Size': '0.00 B',
	  'Airdate': '03/03/1951, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '9',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Casanova Cat',
	  'Size': '0.00 B',
	  'Airdate': '01/06/1951, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '8',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Cue Ball Cat',
	  'Size': '0.00 B',
	  'Airdate': '11/25/1950, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '7',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Framed Cat',
	  'Size': '0.00 B',
	  'Airdate': '10/21/1950, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '6',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Hollywood Bowl',
	  'Size': '0.00 B',
	  'Airdate': '09/16/1950, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '5',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Safety Second',
	  'Size': '0.00 B',
	  'Airdate': '07/01/1950, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '4',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Jerry And The Lion',
	  'Size': '0.00 B',
	  'Airdate': '04/08/1950, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '3',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Texas Tom',
	  'Size': '0.00 B',
	  'Airdate': '03/11/1950, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '2',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Saturday Evening Puss',
	  'Size': '0.00 B',
	  'Airdate': '01/14/1950, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '1',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Little Quacker',
	  'Size': '0.00 B',
	  'Airdate': '01/07/1950, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': 'NFO',
	  'TBN': 'TBN',
	  'Episode': 'Episode',
	  'Absolute': 'Absolute',
	  'Scene Season/Episode': 'Scene Season/Episode',
	  'Scene Absolute': 'Scene Absolute',
	  'Name': 'Name',
	  'Size': 'Size',
	  'Airdate': 'Airdate',
	  'Download': 'Download',
	  'Subtitles': 'Subtitles',
	  'Status': 'Status',
	  'Search': 'Search',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '46',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tennis Chumps',
	  'Size': '0.00 B',
	  'Airdate': '12/10/1949, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '45',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Jerry\'s Diary',
	  'Size': '0.00 B',
	  'Airdate': '10/22/1949, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '44',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Love That Pup',
	  'Size': '0.00 B',
	  'Airdate': '10/01/1949, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '43',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Cat And The Mermouse',
	  'Size': '0.00 B',
	  'Airdate': '09/03/1949, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '42',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Heavenly Puss',
	  'Size': '0.00 B',
	  'Airdate': '07/09/1949, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '41',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Hatch Up Your Troubles',
	  'Size': '0.00 B',
	  'Airdate': '05/14/1949, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '40',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Little Orphan',
	  'Size': '0.00 B',
	  'Airdate': '04/30/1949, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '39',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Polka-Dot Puss',
	  'Size': '0.00 B',
	  'Airdate': '02/26/1949, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '38',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Mouse Cleaning',
	  'Size': '0.00 B',
	  'Airdate': '12/11/1948, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '37',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Professor Tom',
	  'Size': '0.00 B',
	  'Airdate': '10/30/1948, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '36',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Old Rockin\' Chair Tom',
	  'Size': '0.00 B',
	  'Airdate': '09/18/1948, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '35',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Truce Hurts',
	  'Size': '0.00 B',
	  'Airdate': '07/17/1948, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '34',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Kitty Foiled',
	  'Size': '0.00 B',
	  'Airdate': '06/01/1948, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '33',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Invisible Mouse',
	  'Size': '0.00 B',
	  'Airdate': '09/27/1947, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '32',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'A Mouse In The House',
	  'Size': '0.00 B',
	  'Airdate': '08/30/1947, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '31',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Salt Water Tabby',
	  'Size': '0.00 B',
	  'Airdate': '07/12/1947, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '30',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Dr. Jekyll and Mr. Mouse',
	  'Size': '0.00 B',
	  'Airdate': '06/14/1947, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '29',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Cat Concerto',
	  'Size': '0.00 B',
	  'Airdate': '04/26/1947, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '28',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Part Time Pal',
	  'Size': '0.00 B',
	  'Airdate': '03/15/1947, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '27',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Cat Fishin\'',
	  'Size': '0.00 B',
	  'Airdate': '02/22/1947, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '26',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Solid Serenade',
	  'Size': '0.00 B',
	  'Airdate': '08/31/1946, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '25',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Trap Happy',
	  'Size': '0.00 B',
	  'Airdate': '06/29/1946, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '24',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Milky Waif',
	  'Size': '0.00 B',
	  'Airdate': '05/18/1946, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '23',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Springtime For Thomas',
	  'Size': '0.00 B',
	  'Airdate': '03/30/1946, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '22',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Quiet Please!',
	  'Size': '0.00 B',
	  'Airdate': '12/22/1945, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '21',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Flirty Birdy',
	  'Size': '0.00 B',
	  'Airdate': '09/22/1945, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '20',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tee For Two',
	  'Size': '0.00 B',
	  'Airdate': '07/21/1945, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '19',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Mouse In Manhattan',
	  'Size': '0.00 B',
	  'Airdate': '07/07/1945, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '18',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Mouse Comes To Dinner',
	  'Size': '0.00 B',
	  'Airdate': '05/05/1945, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '17',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Mouse Trouble',
	  'Size': '0.00 B',
	  'Airdate': '11/23/1944, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '16',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Puttin\' On The Dog',
	  'Size': '0.00 B',
	  'Airdate': '10/28/1944, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '15',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Bodyguard',
	  'Size': '0.00 B',
	  'Airdate': '07/22/1944, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '14',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Million Dollar Cat',
	  'Size': '0.00 B',
	  'Airdate': '05/06/1944, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '13',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Zoot Cat',
	  'Size': '0.00 B',
	  'Airdate': '02/26/1944, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '12',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Baby Puss',
	  'Size': '0.00 B',
	  'Airdate': '12/25/1943, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '11',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Yankee Doodle Mouse',
	  'Size': '0.00 B',
	  'Airdate': '06/26/1943, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '10',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Lonesome Mouse',
	  'Size': '0.00 B',
	  'Airdate': '05/22/1943, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '9',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Sufferin\' Cats!',
	  'Size': '0.00 B',
	  'Airdate': '01/16/1943, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '8',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Fine Feathered Friend',
	  'Size': '0.00 B',
	  'Airdate': '10/10/1942, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '7',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Bowling Alley-Cat',
	  'Size': '0.00 B',
	  'Airdate': '07/18/1942, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '6',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Puss N\' Toots',
	  'Size': '0.00 B',
	  'Airdate': '05/30/1942, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '5',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Dog Trouble',
	  'Size': '0.00 B',
	  'Airdate': '04/18/1942, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '4',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Fraidy Cat',
	  'Size': '0.00 B',
	  'Airdate': '01/17/1942, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '3',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Night Before Christmas',
	  'Size': '0.00 B',
	  'Airdate': '12/06/1941, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '2',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Midnight Snack',
	  'Size': '0.00 B',
	  'Airdate': '07/19/1941, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '1',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Puss Gets The Boot',
	  'Size': '0.00 B',
	  'Airdate': '02/10/1940, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': 'NFO',
	  'TBN': 'TBN',
	  'Episode': 'Episode',
	  'Absolute': 'Absolute',
	  'Scene Season/Episode': 'Scene Season/Episode',
	  'Scene Absolute': 'Scene Absolute',
	  'Name': 'Name',
	  'Size': 'Size',
	  'Airdate': 'Airdate',
	  'Download': 'Download',
	  'Subtitles': 'Subtitles',
	  'Status': 'Status',
	  'Search': 'Search',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '16',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom & Jerry: Willy Wonka and the Chocolate Factory',
	  'Size': '0.00 B',
	  'Airdate': '06/27/2017, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '15',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom & Jerry: Back to Oz',
	  'Size': '0.00 B',
	  'Airdate': '06/21/2016, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '14',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry: Spy Quest',
	  'Size': '0.00 B',
	  'Airdate': '06/09/2015, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '13',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry: The Lost Dragon',
	  'Size': '0.00 B',
	  'Airdate': '07/27/2014, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '12',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry\'s Giant Adventure',
	  'Size': '0.00 B',
	  'Airdate': '09/09/2013, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '11',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry: Robin Hood and his Merry Mouse',
	  'Size': '0.00 B',
	  'Airdate': '09/28/2012, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '10',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry & the Wizard of Oz',
	  'Size': '0.00 B',
	  'Airdate': '08/14/2011, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '9',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry Meet Sherlock Holmes',
	  'Size': '0.00 B',
	  'Airdate': '08/24/2010, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '8',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'A Nutcracker Tale',
	  'Size': '0.00 B',
	  'Airdate': '10/02/2007, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '7',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry in Shiver Me Whiskers',
	  'Size': '0.00 B',
	  'Airdate': '08/22/2006, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '6',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry: The Fast and the Furry',
	  'Size': '0.00 B',
	  'Airdate': '10/11/2005, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '5',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'The Karate Guard',
	  'Size': '0.00 B',
	  'Airdate': '09/27/2005, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '4',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry: Blast Off to Mars',
	  'Size': '0.00 B',
	  'Airdate': '11/30/2004, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '3',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry: The Magic Ring',
	  'Size': '0.00 B',
	  'Airdate': '03/12/2001, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '2',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry: The Mansion Cat',
	  'Size': '0.00 B',
	  'Airdate': '01/01/2000, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
	{
	  'FIELD1': '',
	  'NFO': '',
	  'TBN': '',
	  'Episode': '1',
	  'Absolute': '-1',
	  'Scene Season/Episode': '',
	  'Scene Absolute': '',
	  'Name': 'Tom and Jerry: The Movie',
	  'Size': '0.00 B',
	  'Airdate': '07/30/1993, 12:00 AM',
	  'Download': '',
	  'Subtitles': '',
	  'Status': 'Skipped',
	  'Search': '',
	},
];

// await onDemand.fromFile(file, title);
// await onDemand.open(file);
// await onDemand.fromDatabase(Episode as unknown as EP);

// onDemand
//     .makeStack()
//     .check()
//     .start();

// onDemand.check();

//     const client = new ChromecastAPI();

// console.log(ffmpeg);
// console.log(ffmpeg.buildCommand());
// ffmpeg.start();

// await storeTvShow({
//     id: 30980,
//     folder: 'M:/Anime/Anime/A.Certain.Magical.Index.(2008)',
//     libraryId: 'cl7i4km1o0004qwef9472dy2t',
// });
// await storeTvShow({
//     id: 30977,
//     folder: 'M:/Anime/Anime/A.Certain.Scientific.Railgun.(2009)',
//     libraryId: 'cl7i4km1o0004qwef9472dy2t',
// });

// const files = readdirSync(`${imagesPath}`);

// for (const image of files) {
//     const stat = statSync(`${imagesPath}/${image}`);

//     if(stat.isDirectory()) continue;

//     if(stat.size == 0){
//         try {
//             rmSync(`${imagesPath}/${image}`);
//         } catch (error) {
//             console.log(error);
//         }
//         continue;
//     }

//     if(!image.endsWith('unknown')) continue;

//     try {
//         renameSync(`${imagesPath}/${image}`, `${imagesPath}/${image.replace('unknown','png')}`);
//     } catch (error) {
//         console.log(error);
//     }
// }

// const tv = await confDb.videoFile.findMany();

// const transaction: any[] = [];

// for (const video of tv) {
//     const newHostFolder = video.hostFolder.replace('Z:/mnt/m/', 'M:/');

//     transaction.push(confDb.videoFile.update({
//         where: {
//             id: video.id,
//         },
//         data: {
//             hostFolder: newHostFolder,
//         },
//     }));

// }

// await confDb.$transaction(transaction);

// const tv = await confDb.videoFile.findMany({
//     where: {
//         subtitles: {
//             contains: 'ass',
//         },
//     },
//     include: {
//         Episode: {
//             select: {
//                 id: true,
//                 tvId: true,
//                 title: true,
//             },
//         },
//     },
// });

// try {
//     const result = tv.map((t) => {
//         return {
//             episodeId: t.Episode?.id,
//             tvId: t.Episode?.tvId,
//             folder: `${t.hostFolder}/fonts`,
//             title: t.Episode?.title,
//         };
//     }).filter((t) => {
//         try {
//             return existsSync(t.folder) && !existsSync(`${t.folder}.json`);
//         } catch (error) {
//             return false;
//         }
//     });

//     for (const file of result) {
//         console.log(file.folder);
//         const files = readdirSync(file.folder)
//             .filter(f => f.endsWith('.ttf') || f.endsWith('.otf'));

//         const res = files.map((f) => {
//             return {
//                 file: f,
//                 mimeType: f.endsWith('.ttf')
//                     ? 'application/x-font-truetype'
//                     : 'application/x-font-opentype',
//             };
//         });

//         writeFileSync(`${file.folder}.json`, JSON.stringify(res));
//     }
// } catch (error) {
//     console.log(error);
// };

// const tv = await confDb.videoFile.findMany();

// try {
//     tv.forEach((t) => {
//         console.log(`${t.hostFolder}`);
//         // if (existsSync(`${t.hostFolder}/metadata`)) {
//         //     rmSync(`${t.hostFolder}/metadata`, { recursive: true });
//         // }

//         const files = readdirSync(`${t.hostFolder}`)
//             .filter(f => f.endsWith('.nfo') || f == 'metadata');

//         for (const file of files) {
//             console.log(`${t.hostFolder}/${file}`);
//             if (existsSync(`${t.hostFolder}/${file}`)) {
//                 rmSync(`${t.hostFolder}/${file}`, { recursive: true });
//             }
//         }
//     });
// } catch (error) {
//     console.log(error);
// }

// };
